services:
  - type: web
    name: horror-stories-backend
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: node dist/index.js
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: CSRF_SECRET
        generateValue: true
    autoDeploy: true

databases:
  - name: horror-stories-db
    databaseName: horror_stories
    plan: starter 
    postgresMajorVersion: 14